version: '3.9'
services:
 api:
  container_name: api
  restart: unless-stopped
  build:
   context: ./api
   dockerfile: Dockerfile
  tty: true 
  networks:
   - app
  volumes:
   - ./api:/app/api
  depends_on:
   - db
  ports:
   - 8000:8000
 dashboard:
  container_name: dashboard
  build:
   context: ./dashboard
   dockerfile: Dockerfile
  tty: true 
  ports:
   - 3000:3000
  volumes:
   - ./dashboard:/app/dashboard
  networks:
   - app
 db:
  container_name: db
  image: mysql
  restart: unless-stopped
  environment:
   MYSQL_DATABASE: ${DB_DATABASE}
   MYSQL_USER: ${DB_USERNAME}
   MYSQL_PASSWORD: ${DB_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  ports:
   - 3307:3306
  networks:
   - app
 phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  restart: unless-stopped
  tty: true
  depends_on:
   - db
  ports:
   - 8088:80
  environment:
    PMA_HOST: ${DB_HOST}
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    UPLOAD_LIMIT: 300M
  networks:
   - app
networks:
 app:
  driver: bridge
 